### PR TITLE
Adding my old HEXO theme and some posts

### PR DESCRIPTION
**Pull request by lorezyra**

### CODE REVIEW

**Comment by lorezyra** [comment]
https://github.com/estruyf/vscode-front-matter/issues/433#issuecomment-1264634125

**Comment by lorezyra** [comment]
Clicked the wrong button...

**Comment by estruyf** [comment]
Can you reproduce the same issue as in https://github.com/estruyf/vscode-front-matter/issues/433?

**Comment by lorezyra** [comment]
Didn't test... just setup the partial blog copy...

**Comment by lorezyra** [comment]
BTW, seems frontmatter really wants the config file and folder on the project root instead of the framework folder (HEXO). It doesn't play well when you have multiple folders for different blog frameworks...

**Pull request closed without merging**
